In [1]:
import pandas as pd

In [3]:
import numpy as np

In [733]:
data = pd.read_csv("IMDB Dataset.csv")

In [735]:
data

     Unnamed: 0                                             review sentiment
0         22287  A bland title disguises this solidly-carpenter...  positive
1         33410  James Cagney is best known for his tough chara...  positive
2            71  Honestly - this short film sucks. the dummy us...  negative
3         15461  Vadim changed Brigitte's image and way of life...  positive
4         13755  I saw this in the summer of 1990. I'm still an...  negative
..          ...                                                ...       ...
995       28033  No spoilers here but I have been a fan since W...  negative
996       31663  The main aspect about the Superstar's movies a...  negative
997       36019  Come on. The new twist is nearly ok, but from ...  negative
998       30061  Visconti's first film has all his trademark vi...  positive
999       36123  How do I begin to review a film that will soon...  negative

[1000 rows x 3 columns]

In [737]:
# sample data - 500
# remove - html
# remove special 
# lowercase
# remove stopwords
# stemming

In [739]:
data = data.sample(500)

In [741]:
data

     Unnamed: 0                                             review sentiment
484       44223  I saw this movie with very low expectations. I...  negative
473       44090  Today You Die was the 4th Seagal movie in a mi...  negative
391       36613  How sheep-like the movie going public so often...  negative
660       41577  What was an exciting and fairly original serie...  negative
509       20023  if you are like me then you will love this gre...  positive
..          ...                                                ...       ...
434       12613  I saw Ray when it first came out. Why? Partly,...  positive
792       46766  I am in awe of the number of people who consid...  negative
684       19218  In the first Howling, we are introduced to a w...  negative
657       46908  Given the budget and the inexperience of every...  negative
896        5446  Vanaja (2006), written and directed by Rajnesh...  positive

[500 rows x 3 columns]

In [743]:
data['sentiment'].unique()

array(['negative', 'positive'], dtype=object)

In [745]:
data['sentiment'].replace({'negative':0, 'positive':1},inplace=True)

C:\Users\niros\AppData\Local\Temp\ipykernel_14340\3970528178.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['sentiment'].replace({'negative':0, 'positive':1},inplace=True)
C:\Users\niros\AppData\Local\Temp\ipykernel_14340\3970528178.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['sentiment'].replace({'negative':0, 'positive':1},inplace=True)

In [747]:
data

     Unnamed: 0                                             review  sentiment
484       44223  I saw this movie with very low expectations. I...          0
473       44090  Today You Die was the 4th Seagal movie in a mi...          0
391       36613  How sheep-like the movie going public so often...          0
660       41577  What was an exciting and fairly original serie...          0
509       20023  if you are like me then you will love this gre...          1
..          ...                                                ...        ...
434       12613  I saw Ray when it first came out. Why? Partly,...          1
792       46766  I am in awe of the number of people who consid...          0
684       19218  In the first Howling, we are introduced to a w...          0
657       46908  Given the budget and the inexperience of every...          0
896        5446  Vanaja (2006), written and directed by Rajnesh...          1

[500 rows x 3 columns]

In [749]:
import re

In [751]:
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean,'',text)

In [753]:
data['review']=data['review'].apply(clean_html)

In [755]:
data

     Unnamed: 0                                             review  sentiment
484       44223  I saw this movie with very low expectations. I...          0
473       44090  Today You Die was the 4th Seagal movie in a mi...          0
391       36613  How sheep-like the movie going public so often...          0
660       41577  What was an exciting and fairly original serie...          0
509       20023  if you are like me then you will love this gre...          1
..          ...                                                ...        ...
434       12613  I saw Ray when it first came out. Why? Partly,...          1
792       46766  I am in awe of the number of people who consid...          0
684       19218  In the first Howling, we are introduced to a w...          0
657       46908  Given the budget and the inexperience of every...          0
896        5446  Vanaja (2006), written and directed by Rajnesh...          1

[500 rows x 3 columns]

In [758]:
def remove_special(text):
    x = ''
    for i in text:
        if i.isalnum():
            x += i
        else:
            x += ' '
    return x

In [760]:
data['review']=data['review'].apply(remove_special)

In [762]:
data

     Unnamed: 0                                             review  sentiment
484       44223  I saw this movie with very low expectations  I...          0
473       44090  Today You Die was the 4th Seagal movie in a mi...          0
391       36613  How sheep like the movie going public so often...          0
660       41577  What was an exciting and fairly original serie...          0
509       20023  if you are like me then you will love this gre...          1
..          ...                                                ...        ...
434       12613  I saw Ray when it first came out  Why  Partly ...          1
792       46766  I am in awe of the number of people who consid...          0
684       19218  In the first Howling  we are introduced to a w...          0
657       46908  Given the budget and the inexperience of every...          0
896        5446  Vanaja  2006   written and directed by Rajnesh...          1

[500 rows x 3 columns]

In [764]:
data['review'].iloc[5]

'In reality that happened  the royal mother in law and father in law lunched with the couple the day after the wedding and gave her the money in public  This troubled young Elisabeth so much that she never forgot the issue  We must remember she was only 16  She was so embarrassed that she kept a fear for sex all her life  Perhaps this began to appear as a trauma  Also the constant meddling of her aunt and mother in law  As you say  she kept all her children away from her  critiqued her teeth and manners  which she considered inappropriate for an empress   and when Sissi finally went to Venice with her husband and children  her eldest daughter died  and the mother in law blamed her for that unfortunate and premature death  She never recovered '

In [766]:
def covert_low(text):
    return text.lower()

In [768]:
data['review']=data['review'].apply(covert_low)

In [770]:
data['review'].iloc[5]

'in reality that happened  the royal mother in law and father in law lunched with the couple the day after the wedding and gave her the money in public  this troubled young elisabeth so much that she never forgot the issue  we must remember she was only 16  she was so embarrassed that she kept a fear for sex all her life  perhaps this began to appear as a trauma  also the constant meddling of her aunt and mother in law  as you say  she kept all her children away from her  critiqued her teeth and manners  which she considered inappropriate for an empress   and when sissi finally went to venice with her husband and children  her eldest daughter died  and the mother in law blamed her for that unfortunate and premature death  she never recovered '

In [772]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\niros\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [774]:
from nltk.corpus import stopwords

In [776]:
a = stopwords.words('english')

In [778]:
a

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [780]:
def remove_stop(text):
    x = []
    for i in text.split():
        if i not in a:
            x.append(i)
        else:
            pass
    return x

In [782]:
data['review']=data['review'].apply(remove_stop)

In [784]:
data['review'].iloc[5]

['reality',
 'happened',
 'royal',
 'mother',
 'law',
 'father',
 'law',
 'lunched',
 'couple',
 'day',
 'wedding',
 'gave',
 'money',
 'public',
 'troubled',
 'young',
 'elisabeth',
 'much',
 'never',
 'forgot',
 'issue',
 'must',
 'remember',
 '16',
 'embarrassed',
 'kept',
 'fear',
 'sex',
 'life',
 'perhaps',
 'began',
 'appear',
 'trauma',
 'also',
 'constant',
 'meddling',
 'aunt',
 'mother',
 'law',
 'say',
 'kept',
 'children',
 'away',
 'critiqued',
 'teeth',
 'manners',
 'considered',
 'inappropriate',
 'empress',
 'sissi',
 'finally',
 'went',
 'venice',
 'husband',
 'children',
 'eldest',
 'daughter',
 'died',
 'mother',
 'law',
 'blamed',
 'unfortunate',
 'premature',
 'death',
 'never',
 'recovered']

In [786]:
from nltk.stem.porter import PorterStemmer

In [788]:
ps = PorterStemmer()

In [790]:
from nltk.stem import PorterStemmer

def stem_words(text):
    ps = PorterStemmer()  # Initialize the stemmer
    x = []
    for i in text:
        x.append(ps.stem(i))
    return x  # Return the result after the loop finishes

In [792]:
data['review']=data['review'].apply(stem_words)

In [794]:
data

     Unnamed: 0                                             review  sentiment
484       44223  [saw, movi, low, expect, know, lot, sure, go, ...          0
473       44090  [today, die, 4th, seagal, movi, mini, marathon...          0
391       36613  [sheep, like, movi, go, public, often, prove, ...          0
660       41577  [excit, fairli, origin, seri, fox, degrad, mea...          0
509       20023  [like, love, great, come, age, teen, movi, thi...          1
..          ...                                                ...        ...
434       12613  [saw, ray, first, came, partli, advertis, hype...          1
792       46766  [awe, number, peopl, consid, film, decent, muc...          0
684       19218  [first, howl, introduc, world, werewolv, exist...          0
657       46908  [given, budget, inexperi, everyon, involv, liv...          0
896        5446  [vanaja, 2006, written, direct, rajnesh, domal...          1

[500 rows x 3 columns]

In [796]:
def join (list_input):
    return ' '.join(list_input)

In [798]:
data['review'].iloc[5]

['realiti',
 'happen',
 'royal',
 'mother',
 'law',
 'father',
 'law',
 'lunch',
 'coupl',
 'day',
 'wed',
 'gave',
 'money',
 'public',
 'troubl',
 'young',
 'elisabeth',
 'much',
 'never',
 'forgot',
 'issu',
 'must',
 'rememb',
 '16',
 'embarrass',
 'kept',
 'fear',
 'sex',
 'life',
 'perhap',
 'began',
 'appear',
 'trauma',
 'also',
 'constant',
 'meddl',
 'aunt',
 'mother',
 'law',
 'say',
 'kept',
 'children',
 'away',
 'critiqu',
 'teeth',
 'manner',
 'consid',
 'inappropri',
 'empress',
 'sissi',
 'final',
 'went',
 'venic',
 'husband',
 'children',
 'eldest',
 'daughter',
 'die',
 'mother',
 'law',
 'blame',
 'unfortun',
 'prematur',
 'death',
 'never',
 'recov']

In [800]:
data['review']=data['review'].apply(join)

In [802]:
data['review'].iloc[5]

'realiti happen royal mother law father law lunch coupl day wed gave money public troubl young elisabeth much never forgot issu must rememb 16 embarrass kept fear sex life perhap began appear trauma also constant meddl aunt mother law say kept children away critiqu teeth manner consid inappropri empress sissi final went venic husband children eldest daughter die mother law blame unfortun prematur death never recov'

In [804]:
X = data['review']
y = data['sentiment']

In [806]:
from sklearn.feature_extraction.text import CountVectorizer

In [808]:
CV = CountVectorizer()

In [812]:
CV.fit_transform(data['review'])

<500x8656 sparse matrix of type '<class 'numpy.int64'>'
	with 44735 stored elements in Compressed Sparse Row format>

In [816]:
X = CV.fit_transform(data['review']).toarray()

In [818]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [820]:
from sklearn.model_selection import train_test_split

In [822]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [826]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix

In [828]:
nb = GaussianNB()

In [830]:
nb.fit(X_train,y_train)

GaussianNB()

In [840]:
y_pred = nb.predict(X_test)

In [842]:
y_test

581    0
492    0
660    0
854    1
445    1
      ..
485    1
200    1
668    1
159    0
528    1
Name: sentiment, Length: 100, dtype: int64

In [844]:
cm = confusion_matrix(y_test,y_pred)

In [846]:
cm

array([[37, 12],
       [18, 33]], dtype=int64)